kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: echo-operator
rules:
- apiGroups:
  - echo.redhat.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-echo-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: echo-operator
  apiGroup: rbac.authorization.k8s.io
